clc;
t=0:0.01:10;
amp_mes=4;
amp_car=6;
freq_car=10;
freq_mes=1;
w=2.*pi.*t;
mes_sig=amp_mes.*sin(2.*pi.*freq_mes.*t);
car_sig=amp_car.*sin(2.*pi.*freq_car.*t);
ysingle=ssbmod(w,freq_car,freq_mes);
subplot(3,1,1);
plot(t,mes_sig);
subplot(3,1,2);
plot(t,car_sig);
subplot(3,1,3)
plot(t,ysingle);
xlabel('time');
ylabel('ysingle');